CAN_PARSER_NODE_PORT: 39010
CAN_STACK_NODE_PORT: 39002
CAN_UDS_NODE_PORT: 39016
CONFIG_NODE_PORT: 39020
DDS_DomainId: 21
DDS_STACK_NODE_PORT: 39026
DOIP_UDS_NODE_PORT: 39022
FIRE2_STACK_NODE_PORT: 39024
LIN_PARSER_NODE_PORT: 39008
LIN_STACK_NODE_PORT: 39006
LOG_REPLAY_NODE_PORT: 39012
PROCESS_NODE_PORT: 39014
SOMEIP_STACK_NODE_PORT: 39004
TCPIP_STACK_NODE_PORT: 39018
XCP_ON_CAN_NODE_PORT: 39028
